ALTER TABLE roles
    MODIFY COLUMN name ENUM('ROLE_ADMIN', 'ROLE_STAFF', 'ROLE_DELIVERY_STAFF', 'ROLE_CUSTOMER') NOT NULL UNIQUE;

UPDATE roles
SET name = 'ROLE_DELIVERY_STAFF'
WHERE name = 'ROLE_STAFF';

ALTER TABLE roles
    MODIFY COLUMN name ENUM('ROLE_ADMIN', 'ROLE_DELIVERY_STAFF', 'ROLE_CUSTOMER') NOT NULL UNIQUE;
