UPDATE roles SET name = 'ROLE_SUPER_ADMIN' WHERE name = 'ROLE_ADMIN';
ALTER TABLE roles MODIFY COLUMN name ENUM('ROLE_SUPER_ADMIN', 'ROLE_STORE_ADMIN', 'ROLE_DELIVERY_STAFF', 'ROLE_CUSTOMER') NOT NULL UNIQUE;
INSERT IGNORE INTO roles (name) VALUES ('ROLE_STORE_ADMIN');
