ALTER TABLE users ADD COLUMN uuid VARCHAR(36) UNIQUE;

UPDATE users SET uuid = UUID() WHERE uuid IS NULL;

ALTER TABLE users MODIFY COLUMN uuid VARCHAR(36) UNIQUE NOT NULL;

CREATE UNIQUE INDEX idx_users_uuid ON users(uuid);
